Update run-sidecar
Co-authored-by: Pokey Rule <755842+pokey@users.noreply.github.com>

diff --git a/run-sidecar b/run-sidecar
--- a/run-sidecar
+++ b/run-sidecar
@@ -13,7 +13,7 @@ if ! [ -x "$(command -v code)" ]; then
     echo 'Error: code is not installed.' >&2
     exit 1
 elif ! [ -x "$(command -v yarn)" ]; then
-    echo 'Error: yarn is not installed.' >&2
+    echo 'ERROR: yarn is not installed. Please install yarn https://yarnpkg.com/getting-started/install' >&2
     exit 1
 fi
 
